### ISSUE TITLE
Inifinte Loading on some Modules

### ISSUE THREAD

**Issue by renanmgs** [kid2407/TranslationEditor#1]
In some modules the loading is infinte, in the console it only says:
`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at EditingDialogue.displayTranslationsForModule (EditingDialogue.js:151)
    at HTMLSelectElement.<anonymous> (EditingDialogue.js:359)
    at HTMLSelectElement.dispatch (jquery.min.js:2)
    at HTMLSelectElement.v.handle (jquery.min.js:2)`

**Comment by kid2407** [comment]
Oh I see what happens there, that should be easily fixed. The problem is that I try to select the language you are using in Foundry first for the module but if it isn't present there is a missing default value.
Thanks for reporting and will be fixed today with an update.

**Comment by renanmgs** [comment]
Im so happy to hear this! Let me know when i can update! =D

**Comment by kid2407** [comment]
And fixed with [Release 1.1.2](https://github.com/kid2407/TranslationEditor/releases/tag/1.1.2), update is pushed and should be available any moment. If it works as intended feel free to close the issue.

**Comment by renanmgs** [comment]
Ty! this issue is now closed! BUt another one has bottering me:
When i try to save some changes an error is shown
![image](https://user-images.githubusercontent.com/30127127/129767195-fd4a0289-9aef-4c0a-8c04-08d7b188562b.png)

**Comment by renanmgs** [comment]
In every module that i try to save, this is question is Enchanced Combat Hud

**Comment by kid2407** [comment]
Let's put that into a new issue, I might have a vague idea what is happening.
