### ISSUE TITLE
Add translation to translation editor

### ISSUE THREAD

**Issue by brunocalado** [kid2407/TranslationEditor#3]
Hi. You did a great job!!! Thank you.

Can you add the Português (Brasil) translation to this module?

[translation-editor-en.txt](https://github.com/kid2407/TranslationEditor/files/7007346/translation-editor-en.txt)

**Comment by kid2407** [comment]
Oh, translations :D
Will add them and thanks for providing them :+1:

**Comment by brunocalado** [comment]
Can you rename **pt.json** to **pt-br.json**?
languages/pt.json

There is small diferences in brazilian portuguese.

**Comment by kid2407** [comment]
oh right, there was something along that line. Though the editor would still only give you it as Portuguese as it is, if I remmeber correctly.

**Comment by brunocalado** [comment]
It should appear like that
![image](https://user-images.githubusercontent.com/4999783/130066508-4477f192-4260-49ac-a6b6-737257cc1123.png)

**Comment by kid2407** [comment]
I mean in the editor, that I save it as a differently named file but still show the proper title in the select for now.

**Comment by kid2407** [comment]
Added with Version 1.1.3.
