### ISSUE TITLE
v9 warning

### ISSUE THREAD

**Issue by brunocalado** [kid2407/TranslationEditor#4]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.x" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by kid2407** [comment]
Thanks for letting me know, I bumped up the compatible version to v9 and pushed a new release: https://github.com/kid2407/TranslationEditor/releases/tag/1.1.4
